parser: babel-eslint

parserOptions:
  ecmaVersion: 2017
  sourceType: module

extends:
  - airbnb/base
  # - plugin:flowtype/recommended
  - plugin:import/errors
  - plugin:import/warnings

env:
  node: true
  mocha: true
